services:
  api:
    build:
      context: .
      network: host
    command: random-coffee-api
    restart: unless-stopped
    ports:
      - ${APPLICATION_HOST}:${APPLICATION_PORT}:8000
    env_file:
      .env
    environment:
      POSTGRES_HOST: database
      REDIS_HOST: broker
      CELERY_CONFIG_MODULE: random_coffee.celeryconfig
    depends_on:
      - database
      - broker
    volumes:
      - .:/app
  database:
    image: "postgres:16"
    env_file:
      .env
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
  broker:
    image: "redis:7"
    ports:
      - mode: ingress
        host_ip: ${REDIS_HOST}
        target: 6379
        published: ${REDIS_PORT}
        protocol: tcp
    volumes:
      - broker:/data
  celery:
    restart: unless-stopped
    build:
      context: .
      network: host
    command: celery worker
    environment:
      REDIS_HOST: broker
      CELERY_CONFIG_MODULE: random_coffee.celeryconfig
    depends_on:
      - broker
volumes:
  database:
  broker:
